server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

swagger:
  uri: ${SWAGGER_URI}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mqtt:
    broker-url: ${MQTT_BROKEN_URL}
    username: ${MQTT_USERNAME}
    password: ${MQTT_PASSWORD}
    topic: ${MQTT_TOPIC}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        dialect: ${JPA_DIALECT}
    show-sql: ${JPA_SHOW_SQL}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION_STATIC}
      s3:
        bucket: ${AWS_S3_BUCKET}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "${OAUTH2_REDIRECT_URI}"
      authorize-uri: ${SECURITY_OAUTH2_AUTHORIZE_URI}
      redirect-uri: ${SECURITY_OAUTH2_REDIRECT_URI}
      client-redirect-uri: ${SECURITY_OAUTH2_CLIENT_REDIRECT_URI}

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}
  session-prefix: ${OPENVIDU_SESSION_PREFIX}

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expire-time:
      access-token: ${SECURITY_JWT_EXPIRE_TIME_ACCESS}
      refresh-token: ${SECURITY_JWT_EXPIRE_TIME_REFRESH}
  whitelist:
    GET: ${SECURITY_WHITELIST_GET}
    POST: ${SECURITY_WHITELIST_POST}
    PUT: ${SECURITY_WHITELIST_PUT}
    DELETE: ${SECURITY_WHITELIST_DELETE}
    PATCH: ${SECURITY_WHITELIST_PATCH}
    OPTIONS: ${SECURITY_WHITELIST_OPTION}
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS}
    allowed-methods: ${SECURITY_CORS_ALLOWED_METHODS}
    allowed-headers: ${SECURITY_CORS_ALLOWED_HEADERS}
    allow-credentials: ${SECURITY_CORS_ALLOW_CREDENTIALS}
    exposed-headers: ${SECURITY_CORS_EXPOSED_HEADERS}
    max-age: ${SECURITY_CORS_MAX_AGE}
  role:
    admin: ${SECURITY_ROLE_ADMIN}
expire-time:
  sign-up-expire-time: ${SING_UP_EXPIRE_TIME}

robot:
  scheduler:
    cron:
      good-morning: ${SCHEDULE_GOOD_MORNING}
      good-night: ${SCHEDULE_GOOD_NIGHT}
      ate-all: ${SCHEDULE_ATE_ALL}
      hungry: ${SCHEDULE_HUNGRY}